name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # หรือเวอร์ชันที่คุณต้องการ

    - name: Install dependencies (if any)
      run: npm install # ถ้าโปรเจกต์ของคุณมี package.json และ dependencies

    - name: Build (if needed)
      run: npm run build # ถ้าโปรเจกต์ของคุณมี build step (เช่น React, Vue)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # โฟลเดอร์ที่ต้องการ publish (./ คือ root ของ repo)
